# pull official base image
FROM node:10.16.1

# set working directory
WORKDIR /usr/src/app

# Copies package.json and package-lock.json to Docker environment
COPY package*.json ./

# Installs all node packages
RUN npm install

# Get IP address as environment variable
ARG REACT_APP_HOST_IP_ADDRESS
ENV REACT_APP_HOST_IP_ADDRESS $REACT_APP_HOST_IP_ADDRESS

# add app
COPY . .

RUN ls
 
# Finally runs the application
CMD [ "npm", "run", "start" ]


