version: '3.7'

services:
  funding:
    build: ./funding
    ports: 
      - 4999:5000
    command: waitress-serve --port=5000 --call 'flaskr:create_app'
    environment:
      - DB=mongodb:27017
    links:
      - mongodb
    depends_on:
      - mongodb
    hostname: funding
  show_and_tell:
    build: ./show_and_tell
    command: waitress-serve --port=5000 --call 'flaskr:create_app'
    hostname: show_and_tell
    ports:
      - 5000:5000
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/usr/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null # --quiet
  frontend:
    build: ./frontend
    ports:
      - 3000:5000
    links:
      - show_and_tell
    command: serve -s build
