version: '3.7'

services:
  funding:
    build: ./funding
    ports: 
      - 4999:5000
    command: flask run --host=0.0.0.0
    environment:
      - FLASK_APP=flaskr
      - DB=mongodb:27017
    links:
      - mongodb
    depends_on:
      - mongodb
  show_and_tell:
    build: ./show_and_tell
    command: python manage.py run -h 0.0.0.0
    ports:
      - 4999:5000
    environment:
      - FLASK_ENV=development
      - FLASK_APP=flaskr
      - PORT=5000
      - FN_AUTH_REDIRECT_URI=http://localhost:5000/google/auth
      - FN_BASE_URI=http://localhost:5000
      - FN_CLIENT_ID=518561222908-6h6um6ldj04kh58g67s7vlv3stvf23d8.apps.googleusercontent.com
      - FN_CLIENT_SECRET=fKfPPcJfQVrWKkQyivOFti0x
      - FN_FLASK_SECRET_KEY=thisisasecret
      - FN_SERVICE_JSON_FILE=google_service_account/graceful-splice-217714-df2055719b16.json
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/usr/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null # --quiet
  frontend:
    build: ./frontend
    stdin_open: true
    expose:
      - 3000
    ports:
      - 3000:3000
    links:
      - show_and_tell
    command: npm run start
